### ISSUE TITLE
Overly restrictive checking on DOI minting

### ISSUE THREAD

**Issue by kauberry** [pacifica/pacifica-metadata#255]
### Pacifica Metadata version
0.12.1

### Pacifica Core Software versions
1.0.0

### Platform Details
Datahub

### Scenario:
Users getting server errors when trying to mint DOI entries

### Steps to Reproduce:
Try to mint a DOI. Fail miserably

### Expected Result:
To not to.

Having issues when users who are members on a proposal try to mint a DOI entry. 500 errors in the doi minting interface (stemming from 400 errors from metadata)

**Comment by GitBytes** [comment]
@dmlb2000 @kauberry So, after some discussion, we determined (if I remember) that the relationships within TransactionUser should really be the `authorized_releaser` and none of the entries should be `member_of`. At least in our case, thus far.

Something we are noticing though is something is putting entries to TransactionUser with `member_of` relationship which may have an effect on this query executing correctly. My thought is if we edit the relationship field of all the TransactionUser entries to be that of `authorized_releaser`, it may just start working again.

At which point, we will need to figure out what is putting entries in as `member_of`. Open to thoughts on this.. Thanks.

**Comment by dmlb2000** [comment]
@GitBytes @kauberry I though behind this is, when the entry is put into `transaction_user` and the relationship should be `authorized_releaser` if you aren't finding a user with this DOI it's because the user transaction relationship is wrong in the database.

https://github.com/EMSL-MSC/pacifica-upload-status/blob/038d94b6e12d12eecc2d2846cfe052bfecc1fa5f/application/controllers/Ajax_api.php#L161

Could that be where the wrong relationship is getting into the metadata model?

**Comment by GitBytes** [comment]
@dmlb2000 @kauberry 
I was able to prove that changing the relationships in transaction_user to the existing `authorized_releaser` relationship fixed the issue we were seeing in the interface. I propose we close this issue as won't fix and not merge #256. The status tool @kauberry I think has the right fixes now to address this as transactions are released going forward.
Cheers!
